[tox]
envlist = py312, py314, flake8

[testenv]
package = editable
basepython =
    py312: python3.12
    py314: python3.14
deps =
           pytest
           coverage
           xmltodict
           -r{toxinidir}/requirements.txt
       -r{toxinidir}/requirements-web.txt
commands = pytest {posargs}

[testenv:flake8]
deps = flake8
commands = flake8 --ignore E402,E226,W605 --max-line-length=100 minemeld tests setup.py

[testenv:stress]
basepython = python3.12
package = editable
deps =
       pytest
       coverage
       xmltodict
       -r{toxinidir}/requirements.txt
       -r{toxinidir}/requirements-web.txt
commands = pytest -m slow {posargs}

[testenv:profile]
basepython = python3.12
package = editable
deps =
       pytest
       pytest-profiling
       coverage
       xmltodict
       -r{toxinidir}/requirements.txt
       -r{toxinidir}/requirements-web.txt
commands = pytest -m slow --profile {posargs}
